version: "3"

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    hostname: mysql-db
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql_root_password"
      - "MYSQL_DATABASE=mysql_database"
      - "MYSQL_USER=mysql_user"
      - "MYSQL_PASSWORD=mysql_password"
      - "TZ='Asia/Tokyo'"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  knowage:
    image: knowagelabs/knowage-server-docker:7.4
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      - "DB_USER=mysql_user"
      - "DB_PASS=mysql_password"
      - "DB_ROOT_PASS=mysql_root_password"
      - "DB_DB=mysql_database"
      - "DB_HOST=mysql-db"
      - "DB_PORT=3306"
      - "HMAC_KEY=aaaaaaaaaa"
      - "PASSWORD_ENCRYPTION_SECRET=encryption_password"
      - "CACHE_DB_HOST=mysql-db"
      - "CACHE_DB_PORT=3306"
      - "CACHE_DB_DB=mysql_database"
      - "CACHE_DB_USER=mysql_user"
      - "CACHE_DB_PASS=mysql_password"
      - "PUBLIC_ADDRESS=localhost"


volumes:
  mysql-data:
  my.cnf:
  initdb.d:
